function displayEvents(displayEventsCall) {
    if (displayEventsCall == 1) {
        for (let i = 0; i < events.length; i++) {
            //console.log(events[i].day)
            let eventHTML = document.getElementById(events[i].day)
            if (eventHTML != undefined) {
                eventHTML.title += events[i].title + ' # '
                eventHTML.insertAdjacentHTML('beforeend', `<span class='${events[i].type}'><span>`)
            }
        }
    }
}
// Feriados para calcular: Páscoa, Corpus Christi, Dia dos Pais
const events = [
    {
        day: '1/0',
        title: 'Ano novo',
        description: `O ano-novo do calendário gregoriano começa em 1º de janeiro (“dia de ano-novo”), assim como era no calendário romano. Existem inúmeros calendários que permanecem em uso em certas regiões do planeta e que calculam a data do ano-novo de forma diferente. A comemoração ocidental tem origem num decreto do líder romano Júlio César, que fixou o 1º de janeiro como o "dia do ano-novo" em 46 a.C..`,
        type: 'event holiday',
    },
    {
        day: '7/0',
        title: 'Dia do Leitor',
        description: `O Dia do Leitor foi criado em homenagem à fundação do jornal cearense “O Povo”, criado em 7 de janeiro de 1928, pelo poeta e jornalista Demócrito Rocha. Neste jornal, que ficou conhecido por combater a corrupção e divulgar fatos políticos, existia um suplemento chamado “Maracajá” que se tornou um espaço de divulgação do movimento modernista literário cearense na época.`,
        type: 'event commemorative',
    },
    {
        day: '15/0',
        title: 'Dia do Adulto',
        description: `No Brasil, um indivíduo é considerado legalmente adulto quando atinge os 18 anos. Isso quer dizer que essa é a idade em que pode responder por todas as suas ações de modo independente. Já para a Biologia, o que define uma pessoa como adulta é a sua capacidade reprodutiva, isso quer dizer que, independente da idade, quando o indivíduo apresenta todas as suas funções reprodutivas ativas, já pode ser considerado um “ser adulto”.`,
        type: 'event commemorative',
    },
    {
        day: '24/0',
        title: 'Dia dos Aposentados',
        description: `Esta data é destinada a homenagear os profissionais que se dedicaram a vida inteira ao trabalho e agora usufruem de um merecido descanso. No nosso país os aposentados desfrutam dos benefícios da previdência social, recebendo do governo uma remuneração por todos os anos de serviços prestados ao país.`,
        type: 'event commemorative',
    },
    {
        day: '30/0',
        title: 'Dia da Saudade',
        description: `Esta data serve para recordar, por exemplo, a memória das pessoas que já partiram, dos que estão distantes, dos tempos bons que já passaram e das lembranças da infância. O léxico "saudade" é exclusivo da língua portuguesa e galega. Uma empresa britânica, que teve a colaboração de mais de mil tradutores, criou uma lista onde constam as palavras mais difíceis de traduzir em todo o mundo. A palavra "saudade" foi considerada a 7ª palavra mais difícil de se traduzir para outros idiomas.`,
        type: 'event commemorative',
    },
    {
        day: '1/1',
        title: 'Dia do publicitário',
        description: `O publicitário é contratado para comunicar a imagem de seus clientes, através de estratégias elaboradas sobre técnicas e pesquisas. Deve atuar dentro dos limites propostos pelo contratante, o que inclui verba disponível e objetivos desejados.`,
        type: 'event commemorative'
    },
    {
        day: '4/1',
        title: 'Dia Mundial do Câncer',
        description: `O objetivo desta data é fazer com que toda a sociedade discuta este assunto, com a principal missão de ajudar a controlar esta doença que mata milhões de pessoas ao redor do mundo. O Dia Mundial do Câncer foi instituído pela União Internacional para o Controle do Câncer (UICC), em 2005, e desde então trabalha para que o maior número de pessoas tenha informações sobre a doença, ajudando principalmente na sua prevenção.`,
        type: 'event commemorative',
    },
    {
        day: '13/1',
        title: 'Dia Mundial do Rádio',
        description: `O Dia Mundial do Rádio é comemorado em 13 de Fevereiro em homenagem à primeira emissão de um programa da United Nations Radio (Rádio das Nações Unidas), em 1946. A transmissão do programa foi em simultâneo para um grupo de seis países. A data foi criada e oficializada em 2011, pela Organização das Nações Unidas para a Educação, Ciência e Cultura (UNESCO). O primeiro Dia Mundial do Rádio foi celebrado apenas em 2012.`,
        type: 'event commemorative',
    },
    {
        day: '14/1',
        title: 'Dias dos Namorados',
        description: `O Dia dos Namorados, em alguns países chamado Dia de São Valentim[1][2][3][4] é uma data especial e comemorativa na qual se celebra a união amorosa entre casais e namorados. Em Portugal e em Angola, assim como em muitos outros países, comemora-se no dia 14 de Fevereiro. No Brasil a data é comemorada no dia 12 de junho, véspera do dia de Santo António de Lisboa, conhecido pela fama de "Santo Casamenteiro"`,
        type: 'event commemorative'
    },
    {
        day: '8/2',
        title: 'Dias Internacional da Mulher',
        description: `A ideia de uma comemoração anual surgiu depois que o Partido Socialista da América organizou o Dia das Mulheres, em 20 de fevereiro de 1909, em Nova York — uma jornada de manifestação pela igualdade de direitos civis e em favor do voto feminino. Em 1975, o dia 8 de março foi instituído como Dia Internacional das Mulheres, pelas Nações Unidas. Atualmente, a data é comemorada em mais de 100 países — como um dia de protesto por direitos ou de edulcorada celebração do feminino, comparável ao Dia das Mães.`,
        type: 'event commemorative',
    },
    {
        day: '21/2',
        title: 'Dia Internacional de Luta pela Eliminação da Discriminação Racial',
        description: `O Dia Internacional de Luta pela Eliminação da Discriminação Racial foi criado pela Organização das Nações Unidas (ONU) e celebra-se em 21 de março em referência ao Massacre de Sharpeville. Em 21 de março de 1960, em Joanesburgo, na África do Sul, 20 000 pessoas faziam um protesto contra a Lei do Passe, que obrigava a população negra a portar um cartão que continha os locais onde era permitida sua circulação. Porém, mesmo tratando-se de uma manifestação pacífica, a polícia do regime de apartheid abriu fogo sobre a multidão desarmada resultando em 69 mortos e 186 feridos.`,
        type: 'event commemorative',
    },
    {
        day: '1/3',
        title: 'Dia da Mentira',
        description: `É uma celebração anual em alguns países europeus e ocidentais, comemorada em 1 de abril, pregando partidas e espalhando boatos como formas de assinalar a data. Uma delas diz que a brincadeira surgiu na França. Em 1564, depois da adoção do calendário gregoriano, o rei Carlos IX de França determinou que o ano novo seria comemorado no dia 1 de janeiro. Alguns franceses resistiram à mudança e continuaram a seguir o calendário antigo, pelo qual o ano se iniciaria a 1 de abril. Gozadores passaram então a ridicularizá-los, a enviar presentes esquisitos e convites para festas que não existiam. Essas brincadeiras ficaram conhecidas como plaisanteries.`,
        type: 'event commemorative',
    },
    {
        day: '2/3',
        title: 'Dia Internacional do Livro Infantil',
        description: `O Dia Internacional do Livro Infantil é um evento internacional comemorado no dia 2 de abril, em função da data em que nasceu o escritor dinamarquês Hans Christian Andersen, em 1805. O autor Hans Christian Andersen foi o primeiro a adaptar fábulas existentes para a linguagem infantil, criando um produto específico para consumo das crianças. As versões mais famosas de clássicos como "O Patinho Feio", "A pequena Sereia" e a "A Polergazinha" são de sua autoria.`,
        type: 'event commemorative',
    },
    {
        day: '7/3',
        title: 'Dia Mundial da Saúde',
        description: `Foi criado pela Organização Mundial da Saúde (OMS) em 7 de abril de 1948, mas passou a ser comemorado apenas a partir de 1950. Seu objetivo geral é apresenta uma oportunidade de mobilizar apoio para a conscientização, ação e pesquisa sobre as prioridades globais da saúde, promovendo a boa saúde e bem estar para todos.`,
        type: 'event commemorative',
    },
    {
        day: '15/3',
        title: 'Titanic afunda no oceano Atlântico',
        description: `O Titanic foi pensado para ser o navio mais luxuoso e mais seguro de sua época, gerando lendas que era supostamente "inafundável". A embarcação partiu em sua viagem inaugural de Southampton com destino a Nova Iorque em 10 de abril de 1912, no caminho passando em Cherbourg-Octeville, na França, e por Queenstown, na Irlanda. Colidiu com um iceberg na proa dianteira do lado direito às 23h40 de 14 de abril, naufragando na madrugada do dia seguinte, com mais de 1.500 pessoas a bordo, sendo um dos maiores desastres marítimos em tempos de paz de toda a história. Seu naufrágio destacou vários pontos fracos do projeto, deficiências nos procedimentos de evacuação de emergência e falhas nas regulamentações marítimas. Comissões de inquérito foram instauradas nos Estados Unidos e no Reino Unido, acarretando mudanças nas leis internacionais de navegação, que permanecem em vigor mais de um século depois`,
        type: 'event historical',
    },
    {
        day: '18/3',
        title: 'Dia do Amigo',
        description: `No Brasil, apesar de não ser instituído por lei, o dia do amigo é também comemorado popularmente em 18 de abril.[5] No entanto, o país também vem adotando a data de 20 de julho, sendo inclusive instituída oficialmente em alguns estados[6][7] e municípios.`,
        type: 'event commemorative',
    },
    {
        day: '18/3',
        title: 'Dia Nacional do Espiríta',
        description: `Espiritismo é uma doutrina espiritualista e reencarnacionista estabelecida na França em meados do século XIX pelo autor e educador Allan Kardec (pseudônimo de Hippolyte Léon Denizard Rivail). Como tal, pretende explicar, a partir de uma perspectiva cristã, o ciclo pelo qual um espírito supostamente retorna à existência material após a morte do antigo corpo em que habitava, além da evolução pela qual ele passa durante este processo.`,
        type: 'event commemorative',
    },
    {
        day: '19/3',
        title: 'Dia do Índio',
        description: `O Dia do Índio, celebrado no Brasil em 19 de abril, foi criado pelo presidente Getúlio Vargas, através do decreto-lei 5.540 de 1943. A data pode ser considerada um motivo de reflexão sobre os valores culturais dos povos indígenas e a importância da preservação e respeito a esses valores.`,
        type: 'event commemorative',
    },
    {
        day: '19/3',
        title: 'Dia do Exército Brasileiro',
        description: `A história do Exército Brasileiro começa oficialmente com o surgimento do Estado brasileiro, ou seja, com a independência do Brasil. Entretanto, mobilizações de brasileiros para guerra existem desde a colonização do Brasil. A data da primeira Batalha dos Guararapes (19 de abril de 1648), no contexto da Insurreição Pernambucana, na qual o exército adversário dos Países Baixos foi formado genuinamente por brasileiros (brancos, negros e ameríndios), é tida simbolicamente como a origem do Exército Brasileiro`,
        type: 'event commemorative',
    },
    {
        day: '22/3',
        title: 'Dia Mundial do Planeta Terra',
        description: 'O Dia da Terra, cuja finalidade é criar uma consciência comum aos problemas da contaminação, conservação da biodiversidade e outras preocupações ambientais para proteger a Terra, foi criado pelo senador norte-americano Gaylord Nelson, no dia 22 de Abril de 1970.',
        type: 'event commemorative',
    },
    {
        day: '22/3',
        title: 'Dia do Descobrimento do Brasil',
        description: `Este momento é muitas vezes entendido como sendo o do avistamento da terra que então denominaram por Ilha de Vera Cruz, nas imediações do Monte Pascoal, pela armada comandada por Pedro Álvares Cabral, ocorrida no dia 22 de abril de 1500. Esta descoberta inscreve-se nos chamados descobrimentos portugueses. Embora quase exclusivamente utilizado em relação à viagem de Pedro Álvares Cabral, o termo "descoberta do Brasil" pode também aplicar-se à chegada da expedição do navegador e explorador espanhol Vicente Yáñez Pinzón, que atingiu o cabo de Santo Agostinho, promontório localizado no atual estado de Pernambuco, em 26 de janeiro de 1500. Trata-se da mais antiga viagem comprovada ao território brasileiro. Entretanto, a navegação de navios castelhanos ao longo da costa americana não produziu consequências. A chegada de Pinzón pode ser vista como um simples incidente da expansão marítima espanhola`,
        type: 'event holiday',
    },
    {
        day: '23/3',
        title: 'Dia Mundial do Escoteiro',
        description: `O escotismo foi fundado em 1907 por Robert Stephenson Smyth Baden-Powell. É um movimento juvenil mundial, educacional, voluntariado, apartidário e sem fins lucrativos. A sua proposta é o desenvolvimento do jovem, por meio de um sistema de valores que prioriza a honra, baseado na Promessa (ou Compromisso) e na Lei escoteira, e através da prática do trabalho em equipe e da vida ao ar livre, fazendo com que o jovem assuma seu próprio crescimento, tornando-se um exemplo de fraternidade, lealdade, companheirismo, altruísmo, responsabilidade, respeito e disciplina.`,
        type: 'event commemorative',
    },
    {
        day: '28/3',
        title: 'Dia da Sogra',
        description: `Sogra é como é chamada a mãe do cônjuge. Na cultura popular moderna, a sogra é vista como um peso a ser carregado e muitas vezes, a palavra acaba por adquirir sentido pejorativo. No Brasil, o cantor Dicró ficou famoso por fazer músicas onde conta piadas a respeito da própria sogra, piadas estas que costumam sempre ser muito populares entre comediantes do mesmo país.`,
        type: 'event commemorative',
    },
    {
        day: '1/4',
        title: 'Dia Mundial da Língua Portuguesa',
        description: `A data foi criada como Dia da Língua Portuguesa e da Cultura pela Comunidade dos Países de Língua Portuguesa a 20 de julho de 2009, por resolução da XIV Reunião Ordinária do Conselho de Ministros da CPLP, decorrida na cidade da Praia, Cabo Verde.`,
        type: 'event commemorative',
    },
    {
        day: '1/4',
        title: 'Dia do Trabalhador',
        description: `É uma data comemorativa internacional, dedicada aos trabalhadores, celebrada anualmente no dia 1 de maio em quase todos os países do mundo, sendo feriado em muitos deles.`,
        type: 'event holiday',
    },
    {
        day: '5/4',
        title: 'Morre Napoleão Bonaparte',
        description: `Napoleão foi um estadista e líder militar francês que ganhou destaque durante a Revolução Francesa e liderou várias campanhas militares de sucesso durante as Guerras Revolucionárias Francesas. Foi imperador dos franceses como Napoleão I de 1804 a 1814 e brevemente em 1815 durante os Cem Dias.`,
        type: 'event historical',
    },
    {
        day: '8/4',
        title: 'Dia da Vitória na Europa (Europa Ocidental)',
        description: `Dia da Vitória na Europa foi o dia 8 de Maio de 1945, data formal da derrota da Alemanha Nazi em favor dos Aliados na Segunda Guerra Mundial. A data foi motivo de grandes celebrações, especialmente em Londres, onde mais de um milhão de pessoas festejaram o fim da guerra na Europa, embora os racionamentos de comida e vestuário continuassem por mais uma série de anos. `,
        type: 'event historical',
    },
    {
        day: '9/4',
        title: 'Dia da Vitória na Europa (Europa Oriental)',
        description: `O Dia da Vitória Soviética ou 9 de maio marca a capitulação da Alemanha Nazista para a União Soviética na Segunda Guerra Mundial (também conhecida como a Grande Guerra Patriótica na União Soviética e os Estados pós-soviéticos). Foi primeiro celebrado em quinze Repúblicas da União Soviética, após a assinatura do documento de entrega no final da noite de 8 de maio de 1945 (9 de maio na hora de Moscou).`,
        type: 'event commemorative',
    },
    {
        day: '13/4',
        title: 'Abolição da Escravatura',
        description: `Esta data comemora o fim da escravidão no Brasil oficialmente através da Lei Áurea, sancionada em 13 de maio de 1888. Quem assinou a Lei da Abolição da Escravatura foi Princesa Isabel, princesa imperial do Brasil. Não se trata de feriado nacional, sendo esta condição revogada através da Lei nº 19.488, em 15 de dezembro de 1930, pelo ex-presidente Getúlio Vargas.`,
        type: 'event commemorative',
    },
    {
        day: '16/4',
        title: 'Dia do Gari',
        description: `O Dia do Gari é comemorado anualmente em 16 de maio, em todo o Brasil. Esta data tem o objetivo de homenagear os profissionais responsáveis em manter as ruas, praças e praias limpas de todo o lixo gerado naturalmente ou por ação do ser humano.`,
        type: 'event commemorative',
    },
    {
        day: '17/4',
        title: 'Dia Internacional contra a Homofobia, a Transfobia e a Bifobia',
        description: `É comemorado no dia 17 de maio e tem como objetivo coordenar eventos internacionais que aumentem a conscientização sobre as violações dos direitos LGBT e estimulem o interesse pelo trabalho pelos direitos LGBT em todo o mundo.`,
        type: 'event commemorative',
    },
    {
        day: '25/4',
        title: 'Nasce Papa João Paulo II',
        description: `O Dia da Toalha é celebrado no dia 25 de maio como uma homenagem dos fãs ao autor da série O Guia do Mochileiro das Galáxias, Douglas Adams.`,
        type: 'event commemorative',
    },
    {
        day: '28/4',
        title: 'Dia do Hambúrguer',
        description: `O Dia mundial do Hambúrguer é comemorado em 28 de maio. O hambúrguer é uma das carnes mais populares em todo mundo e teria sido criado na Alemanha, na cidade de Hamburgo e daí a origem do seu nome.`,
        type: 'event commemorative',
    },
    {
        day: '31/4',
        title: 'Dia Mundial sem Tabaco',
        description: `É uma data celebrada anualmente no dia 31 de maio. Criada pelos Estados membros da Organização Mundial da Saúde, a campanha tem como objetivo chamar a atenção para a epidemia do tabaco e para as mortes que causa, informando o público sobre os perigos do uso do tabaco, as estratégias da indústria do tabaco e as ações da Organização Mundial da Saúde para o controle do tabagismo.`,
        type: 'event commemorative',
    },
    {
        day: '5/5',
        title: 'Dia Nacional da Reciclagem',
        description: `O Dia Nacional da Reciclagem é celebrado anualmente em 5 de junho. O objetivo desta data é conscientizar as pessoas sobre a importância de coletar, separar e destinar os materiais recicláveis, como embalagens plásticas, cartões, peças eletrônicas, etc.`,
        type: 'event commemorative',
    },
    {
        day: '5/5',
        title: 'Dia Mundial do Meio Ambiente',
        description: `É comemorado anualmente em 5 de Junho e tem como objetivo promover atividades de proteção e preservação do meio ambiente. Todos os anos, as Nações Unidas dão um tema diferente ao Dia Mundial do Meio Ambiente. Esta foi a forma encontrada pela ONU para dar ideias de atividades que promovam a conscientização da população para preservar o meio ambiente.`,
        type: 'event commemorative',
    },
    {
        day: '8/5',
        title: 'Dia Mundial dos Oceanos',
        description: `O Dia Mundial dos Oceanos (World Ocean Day) é celebrado em 8 de junho. O objetivo desta data é relembrar a importância dos oceanos para o equilíbrio da vida no planeta Terra. E, para isso, são realizadas várias atividades de conscientização civil sobre os perigos enfrentados atualmente pelos oceanos.`,
        type: 'event commemorative',
    },
    {
        day: '9/5',
        title: 'Dia do Porteiro',
        description: `A data celebra os profissionais responsáveis pela segurança e bom funcionamento dos prédios comerciais e residenciais. Controla a entrada e saída das pessoas nos prédios e, em muitos casos, auxilia em outros serviços inerentes ao bom funcionamento do estabelecimento ou do bom convívio residencial. A Federação Nacional dos Sindicatos de Trabalhadores de Edifícios e Condomínios, que abrange os Porteiros, definiu a data comemorativa para a classe como sendo o dia 09 de Junho, no entanto, não se sabe ao certo as razões para a escolha específica deste dia.`,
        type: 'event commemorative',
    },
    {
        day: '12/5',
        title: 'Dia dos Namorados',
        description: `No Brasil, a data foi criada pelo publicitário João Doria, sendo comemorada no dia 12 de Junho por ser véspera do 13 de Junho, Dia de Santo António, santo português com tradição de casamenteiro.`,
        type: 'event commemorative',
    },
    {
        day: '12/5',
        title: 'Dia Mundial de Combate ao Trabalho Infantil',
        description: `O principal objetivo da data é alertar a comunidade em geral e os diferentes núcleos do governo sobre a realidade do trabalho infantil, uma prática que se mantém corriqueira em diversas regiões do Brasil e do mundo. Esta data foi criada por iniciativa da Organização Internacional do Trabalho, uma agência vinculada à Organização das Nações Unidas (ONU), em 2002.`,
        type: 'event commemorative',
    },
    {
        day: '14/5',
        title: 'Dia Mundial do Doador de Sangue',
        description: `A data foi criada por iniciativa da Organização Mundial da Saúde (OMS), em 2014, e o dia escolhido é uma homenagem ao nascimento de Karl Landsteiner (14 de junho de 1868 - 26 de junho de 1943), um imunologista austríaco que descobriu o fator Rh e várias diferenças entre os diversos tipos sanguíneos.`,
        type: 'event commemorative',
    },

    {
        day: '19/5',
        title: 'Dia Nacional do Cinema Brasileiro',
        description: `Esta data é comemorada em 19 de junho em homenagem ao dia em que o ítalo-brasileiro Afonso Segreto – o primeiro cinegrafista e diretor do país – registrou as primeiras imagens em movimento no território brasileiro, em 1898. Afonso Segreto fez imagens da entrada da baía de Guanabara, no Rio de Janeiro, a bordo do navio francês Brésil - a primeira filmagem em território nacional.`,
        type: 'event commemorative',
    },
    {
        day: '21/5',
        title: 'Nasce Machado de Assim',
        description: `Joaquim Maria Machado de Assis (1839 – 1908) foi um escritor brasileiro, considerado por muitos críticos, estudiosos, escritores e leitores o maior nome da literatura brasileira. Testemunhou a Abolição da escravatura e a mudança política no país quando a República substituiu o Império, além das mais diversas reviravoltas pelo mundo em finais do século XIX e início do XX, tendo sido grande comentador e relator dos eventos político-sociais de sua época.`,
        type: 'event historical',
    },
    {
        day: '24/5',
        title: 'Dia Mundial do Disco Voador',
        description: `A data foi criada a partir de um fato ocorrido em 24 de Junho de 1947, quando o piloto americano Kenneth Arnold disse ter avistado nove objetos voadores não identificados próximos a uma montanha em Washington. O que chamou mais atenção para o caso foi o que aconteceu poucos dias depois. Uma suposta nave alien teria caído no estado norte-americano do Novo México, e com ela teriam sido encontrados corpos de seres alienígenas. A história ficou mundialmente conhecida, sendo ainda hoje uma referência no mundo da ufologia, como o Caso Roswell.`,
        type: 'event commemorative',
    },
    {
        day: '25/5',
        title: 'Dia do Imigrante',
        description: `A imigração é um fenômeno que ocorre quando há o deslocamento de grupos de indivíduos das regiões / países em que nasceram para terras estrangeiras. Esta data foi criada para homenagear essas pessoas, que deixam para trás amigos e família em busca de melhores condições de vida, além de colaborarem para o crescimento do país que se destinam.`,
        type: 'event commemorative',
    },
    {
        day: '25/5',
        title: 'Morre Michael Jackson',
        description: `Michael Joseph Jackson (1958 — 2009) foi um cantor, compositor e dançarino estadunidense. Apelidado de "Rei do Pop", foi um dos ícones culturais mais importantes e influentes de todos os tempos e um dos maiores artistas da história da música. O oitavo filho da família Jackson, Michael fez sua estreia profissional em 1964, com seus irmãos mais velhos, Jackie, Tito, Jermaine e Marlon, como membro do grupo musical The Jackson 5.`,
        type: 'event historical',
    },
    {
        day: '28/5',
        title: 'Dia Internacional do Orgulho Gay',
        description: `O Dia do Orgulho LGBT foi criado e é celebrado em 28 de junho em homenagem a um dos episódios mais marcantes na luta da comunidade gay pelos seus direitos: a Rebelião de Stonewall Inn. Em 1969, esta data marcou a revolta da comunidade LBGT contra uma série de invasões da polícia de Nova York aos bares que eram frequentados por homossexuais, que eram presos e sofriam represálias por parte das autoridades.`,
        type: 'event commemorative',
    },
    {
        day: '29/5',
        title: 'Dia do Dublador',
        description: `Esta data é uma homenagem aos artistas que utilizam o talento da interpretação para transmitir as emoções dos seus personagens através da voz. Os dubladores são profissionais que dublam as versões criadas dos diálogos de filmes, desenhos e seriados de outros idiomas para a língua portuguesa.`,
        type: 'event commemorative',
    },
    {
        day: '2/6',
        title: 'Idependência da Bahia',
        description: `As lutas pela emancipação tiveram início na Bahia, ainda em 1821 e, mesmo após a declaração de independência do Brasil, em 7 de setembro de 1822, o estado continuou em luta contra as tropas portuguesas até a rendição destas, ocorrida no dia 2 de julho de 1823, após diversas batalhas. A data, feriado estadual, é comemorada pelos baianos como o Dia da Independência da Bahia.`,
        type: 'event historical',
    },
    {
        day: '7/6',
        title: 'Dia Mundial do Chocolate',
        description: `Não se sabe ao certo o motivo da escolha do dia 7 de julho para celebrar esta data. No entanto, acredita-se que marque a introdução do chocolate na Europa, por volta do século XV. Outrora, o chocolate só era conhecido e utilizado pelos Maias e os Astecas, civilizações originárias da América. Tomar chocolate quente virou, então, símbolo de status para a aristocracia europeia e somente com a Revolução Industrial o produto foi popularizado.`,
        type: 'event commemorative',
    },
    {
        day: '10/6',
        title: 'Dia da Pizza',
        description: `O Dia da Pizza é comemorado em 10 de julho, quando a data foi instituída pelo então secretário de turismo Caio Luís de Carvalho, em 1985. Foi feito um concurso estadual em São Paulo que elegeria as 10 melhores receitas de mussarela e margherita. Empolgado com o sucesso do evento, o secretário escolheu a data de seu encerramento, 10 de julho, como data oficial de comemoração.`,
        type: 'event commemorative',
    },
    {
        day: '13/6',
        title: 'Dia Mundial do Rock',
        description: `Em 13 de julho de 1985, houve um grande evento chamado Live Aid, um show simultâneo em Londres, na Inglaterra, e na Filadélfia, nos Estados Unidos. O objetivo principal era conscientizar a população mundial sobre a drástica pobreza e a fome na Etiópia. O show foi transmitido ao vivo para diversos países. Na ocasião, o cantor e baterista Phil Collins propôs que o dia 13 de julho fosse lembrando como Dia Mundial do Rock.`,
        type: 'event commemorative',
    },
    {
        day: '17/6',
        title: 'Dia Mundial do Emoji',
        description: `O Dia Mundial do Emoji é "uma criação de Jeremy Burge", segundo a CNBC, que afirmou que o "fundador da Emojipédia, com sede em Londres, o criou" em 2014. O The New York Times informou que Burge criou isso em 17 de julho "com base na maneira como o emoji do calendário é mostrado nos iPhones". No primeiro Dia Mundial do Emoji, Burge disse ao The Independent "que não havia planos formais" a não ser escolher a data. O The Washington Post sugeriu em 2018 que os leitores usem esse dia para "se comunicar apenas com emojis".`,
        type: 'event commemorative',
    },
    {
        day: '18/6',
        title: 'Dia Internacional de Nelson Mandela',
        description: `Por meio da Resolução A/RES/64/13 a ONU, com o consenso de 192 países membros, homenageia a dedicação de Mandela a serviço da humanidade, pela resolução de conflitos, pela relação entre as raças, promoção e proteção dos direitos humanos, a reconciliação, igualdade de gêneros e direitos das crianças e outros grupos vulneráveis, e ainda pelo desenvolvimento das comunidades pobres ou subdesenvolvidas.`,
        type: 'event commemorative',
    },
    {
        day: '20/6',
        title: 'Chegada do Homem à Lua',
        description: `No dia 16 de julho de 1969, três astronautas chamados Neil Armstrong, Michael Collins e Edwin Aldrin decolam dos Estados Unidos da América em direção à Lua a bordo da espaçonave Apolo 11. A viagem dura 4 dias. No dia 20 Armstrong, o comandante da missão, pisa na Lua e diz a famosa frase: "Este é um pequeno passo para um homem; um salto gigantesco para a humanidade", minutos depois, uma bandeira americana é colocada na Lua.`,
        type: 'event historical',
    },
    {
        day: '23/6',
        title: 'Nasce Santos Dumont,',
        description: `Alberto Santos Dumont (1873 — 1932) foi um aeronauta, esportista, autodidata e inventor brasileiro. Santos Dumont também foi o primeiro a decolar a bordo de um avião impulsionado por um motor a gasolina. Em 23 de outubro de 1906 voou cerca de sessenta metros a uma altura de dois a três metros com o Oiseau de Proie (francês para "ave de rapina"), no Campo de Bagatelle, em Paris. Menos de um mês depois, em 12 de novembro, diante de uma multidão de testemunhas, percorreu 220 metros a uma altura de seis metros com o Oiseau de Proie III. O título de responsável pelo primeiro voo num avião, atribuído por brasileiros a Santos Dumont, é disputado com outros pioneiros, nomeadamente os irmãos Wright. Na França, costuma-se atribuir o feito a Clément Ader, que teria efetuado o primeiro voo de um equipamento mais pesado que o ar propulsionado a motor e levantando voo pelos seus próprios meios em 9 de outubro de 1890, mas teve suas alegações refutadas pelo Ministério da Guerra do Exército Francês.`,
        type: 'event historical',
    },
    {
        day: '1/7',
        title: 'Dia Mundial da Amamentação',
        description: `O dia mundial da amamentação é comemorado em 1 de agosto, data escolhida pela Aliança Mundial de Ação pró-Amamentação (World Alliance for Breastfeeding Action – WABA) em evento realizado na cidade de Nova Iorque no ano de 1991. Inicialmente, a data visava comemorar a Declaração de Innocenti, que trata da necessidade do aleitamento materno no combate à mortalidade infantil, aprovada em 1 de agosto de 1990 pela Organização Mundial da Saúde (OMS) e pelo Fundo das Nações Unidas para a Infância (Unicef) .`,
        type: 'event commemorative',
    },
    {
        day: '9/7',
        title: 'Dia Internacional dos Povos Indígenas',
        description: `O principal propósito desta data é conscientizar sobre a inclusão dos povos indígenas na sociedade, alertando sobre seus direitos, pois muitas vezes são marginalizados ou excluídos da cidadania. Outra finalidade é garantir a preservação da cultura tradicional de cada um dos povos indígenas, como fonte primordial de sua identidade.`,
        type: 'event commemorative',
    },
    {
        day: '13/7',
        title: 'Dia Mundial do Canhoto',
        description: `O Dia Mundial do Canhoto é comemorado anualmente em 13 de agosto. A data surgiu no Reino Unido e foi criada com o intuito de conscientizar as pessoas sobre os desafios que um canhoto enfrenta em uma sociedade onde 90% da população é destra.`,
        type: 'event commemorative',
    },
    {
        day: '15/7',
        title: 'Dia do Solteiro',
        description: `A origem da data é desconhecida, mas já que existe o Dia dos Namorados, alguém achou que seria interessante existir uma data destinada para as pessoas que não têm um parceiro ou parceira na vida amorosa.`,
        type: 'event commemorative',
    },
    {
        day: '19/7',
        title: 'Dia Mundial da Fotografia',
        description: `A escolha do dia 19 de agosto para celebrar esta data é uma homenagem à invenção do daguerreótipo, o antecessor das câmeras fotográficas. Foi em 19 de agosto de 1839 que a Academia Francesa de Ciências anunciava mundialmente a nova invenção. Este aparelho foi desenvolvido pelo francês Louis Daguerre (1787-1851), em 1837, graças aos estudos de Joseph Niépce (1765-1833), que havia criado a héliographie alguns anos antes.`,
        type: 'event commemorative',
    },
    {
        day: '20/7',
        title: 'Dia do Maçom',
        description: `De acordo com a história maçônica, no dia 20 de Agosto de 1822 aconteceu uma sessão histórica entre as Lojas de Maçonaria "Comércio e Artes" e "União e Tranquilidade", na cidade do Rio de Janeiro. Na ocasião, o Irmão Gonçalves Ledo teria feito um discurso emocionante e inspirador, pedindo a Independência do Brasil ainda naquele ano.`,
        type: 'event commemorative',
    },
    {
        day: '5/8',
        title: 'Dia do Irmão',
        description: `No Brasil, o dia do irmão é tradicionalmente celebrado em 5 de setembro. No entanto, não há um registro que oficialize a data no país. O dia surgiu por iniciativa da Igreja Católica, que homenageia o aniversário de morte da missionária Madre Teresa de Calcutá, desde 2007 - data que completou 10 anos do seu falecimento. No contexto religioso, o sentido da palavra "irmão" está ligada ao "próximo". Portanto, esse dia serve para incentivar as pessoas a repensarem as atitudes perante os outros seres humanos, sendo mais humildes, companheiras e gentis.`,
        type: 'event commemorative',
    },
    {
        day: '7/8',
        title: 'Dia da Independência do Brasil',
        description: `Próximo Dia da Independência do Brasil - 7 de Setembro 7 de Setembro de 2022 (Quarta-feira)
        O Dia da Independência do Brasil celebra a data em que o Brasil se tornou independente de Portugal, o que aconteceu em 7 de setembro de 1822. Popularmente conhecido como o 7 de setembro, é um feriado nacional, também chamado de Dia da Pátria. Nessa data, os brasileiros comemoram a ocasião em que Dom Pedro proclamou a independência do Brasil gritando "independência ou morte", ato que ficou conhecido como o Grito da Independência ou Grito do Ipiranga, porque foi dado às margens do riacho Ipiranga, em São Paulo.`,
        type: 'event holiday',
    },
    {
        day: '8/8',
        title: 'Dia Mundial da Alfabetização',
        description: `Com o propósito de fomentar a alfabetização nos vários países, a Organização das Nações Unidas (ONU) e a Organização das Nações Unidas para a Educação, a Ciência e a Cultura (UNESCO) instituíram esta data em 1967. O processo da aprendizagem de ler e escrever (alfabetização) está diretamente relacionado com o desenvolvimento de um país, conforme indicam pesquisas na área. Quanto mais pessoas analfabetas, menor é o índice de desenvolvimento. O Brasil ainda celebra o Dia Nacional da Alfabetização em 14 de novembro.`,
        type: 'event commemorative',
    },
    {
        day: '9/8',
        title: 'Dia do Cachorro-Quente',
        description: `Acredita-se que o Dia do Cachorro-Quente seja uma homenagem à suposta data de criação deste tipo de sanduíche, em 9 de setembro de 1884, na cidade de Nova York. O cachorro quente teria sido inventado por um imigrante alemão. Ele teve a incrível (e simples) ideia de colocar uma salsicha dentro de um pão, que é uma forma bem prática de se alimentar.`,
        type: 'event commemorative',
    },
    {
        day: '15/8',
        title: 'Dia do Cliente',
        description: `O Dia do Cliente foi criado em 2003, no estado do Rio Grande do Sul, pelo empresário gaúcho João Carlos Rego, especialista em Marketing e Recursos Humanos. Sua ideia era criar uma data diferenciada onde os clientes pudessem ser homenageados, ajudando a desenvolver uma relação de fidelidade entre os consumidores e os comerciantes. O Dia do Cliente foi oficializado no Rio Grande do Sul em 2003, mas atualmente já foi aprovado em 14 estados brasileiros e 167 municípios.`,
        type: 'event commemorative',
    },
    {
        day: '23/8',
        title: 'Dia dos Filhos',
        description: `Esta data foi criada com o intuito de ajudar a fortalecer os laços filiais que ligam pais e filhos. No agitado mundo contemporâneo, muitos pais trabalham muito e acabam por não aproveitar os momentos livres para acompanhar o cotidiano e relação com seus próprios filhos e filhas.`,
        type: 'event commemorative',
    },
    {
        day: '26/8',
        title: 'Dia Nacional dos Surdos',
        description: `A escolha do 26 de setembro é uma homenagem à criação da primeira Escola de Surdos do Brasil, em 1857, na cidade do Rio de Janeiro, que atualmente é conhecida como INES (Instituto Nacional de Educação de Surdos).`,
        type: 'event commemorative',
    },
    {
        day: '29/8',
        title: 'Dia Mundial do Petróleo',
        description: `O Dia Mundial do Petróleo é comemorado em 29 de setembro. A data é destinada a homenagear um dos minerais mais importantes para o desenvolvimento tecnológico da sociedade no final do século XIX e começo do XX: o petróleo. Conhecido como o "ouro negro", o petróleo é um óleo natural formado dentro de rochas sedimentares, a partir da decomposição de compostos orgânicos há milhões de anos, como animais e plantas, por exemplo.`,
        type: 'event commemorative',
    },
    {
        day: '1/9',
        title: 'Dia Mundial da Música',
        description: `A ideia para criar o Dia Mundial da Música surgiu a partir de uma iniciativa da UNESCO, em 1975, através da International Music Council – uma organização não-governamental, fundada em 1949, e que tem o objetivo de promover a paz e a amizade entre os povos com o auxílio da música.`,
        type: 'event commemorative',
    },
    {
        day: '2/9',
        title: 'Dia Internacional da Não-Violência',
        description: `Esta data foi criada pela ONU (Organização das Nações Unidas), em homenagem à figura de Mahatma Gandhi, um dos principais representantes na luta pelo pacifismo e no respeito dos direitos humanos e da justiça. Gandhi foi assassinado em 30 de janeiro de 1948, por consequência da sua tentativa de unificar pacificamente os povos hindus com os muçulmanos. Gandhi nasceu em 2 de outubro de 1869, sendo a escolha desta data como o Dia Internacional da Não-Violência.`,
        type: 'event commemorative',
    },
    {
        day: '7/9',
        title: 'Dia Mundial do Sorriso',
        description: `O Dia Mundial do Sorriso foi comemorado pela primeira vez em 1999 e, desde então, vem ganhando adeptos. No Brasil, as empresas fazem campanhas publicitárias específicas e aproveitam a data para comunicar seus produtos aos consumidores. A data foi criada a pedido do desenhista americano Harvey Ball (1921-2001), autor do círculo amarelo sorridente, que se tornou um ícone mundial.`,
        type: 'event commemorative',
    },
    {
        day: '12/9',
        title: 'Dia das Crianças',
        description: `A proposta para a criação desta data é de autoria do deputado federal fluminense Galdino do Valle Filho. Após a sua aprovação, surgiu o Decreto nº 4867, de 5 de novembro de 1924, que oficializou o dia 12 de outubro como o Dia das Crianças. No entanto, o dia ganhou maior popularidade a partir de 1960, quando a Fábrica de Brinquedos Estrela fez uma promoção com a Johnson & Johnson e criou a "Semana do Bebê Robusto" a fim de aumentarem suas vendas. A partir deste momento, a data passou a ser marcada pela oferta de presentes às crianças, principalmente brinquedos.`,
        type: 'event commemorative',
    },
    {
        day: '12/9',
        title: 'Nossa Senhora Aparecida',
        description: `Esta é a data que homenageia a padroeira do Brasil, que também é um dos principais santos do catolicismo. Nossa Senhora da Conceição Aparecida, foi proclamada Rainha do Brasil e sua Padroeira Oficial em 16 de julho de 1930, por decreto do Papa Pio e, 50 anos depois, foi decretado oficialmente que o dia 12 de outubro seria feriado oficial no país.`,
        type: 'event holiday',
    },
    {
        day: '15/9',
        title: 'Dia do Professor',
        description: `O dia 15 de outubro foi escolhido para comemorar o dia do professor, pois em 15 de outubro de 1827, Dom Pedro I, Imperador do Brasil, decretou uma Lei Imperial responsável pela criação do Ensino Elementar no Brasil (do qual chamou “Escola de Primeiras Letras”), e através deste decreto todas as cidades deveriam ter suas escolas de primeiro grau.`,
        type: 'event commemorative',
    },
    {
        day: '18/9',
        title: 'Dia do Médico',
        description: `O Dia do Médico é celebrado em 18 de outubro em homenagem a São Lucas, o padroeiro dos médicos. Lucas foi um dos quatro evangelistas do Novo Testamento, e seu evangelho é o terceiro em ordem cronológica. Lucas era médico, razão pela qual se decidiu homenagear os profissionais com o mesmo dia da festa deste santo.`,
        type: 'event commemorative',
    },
    {
        day: '22/9',
        title: 'Dia Internacional de Atenção à Gagueira',
        description: `A data tem o objetivo de informar as pessoas sobre o que é a gagueira e como ajudar a tratar este que é considerado um distúrbio ou transtorno de fluência da fala. O principal problema da gagueira é a dificuldade que o cérebro tem de finalizar o som de uma palavra e começar a próxima logo em seguida, fazendo com que as pessoas tenham dificuldades para se expressar, demorem para completar uma frase, repetindo muitas vezes as mesmas sílabas.`,
        type: 'event commemorative',
    },
    {
        day: '28/9',
        title: 'Dia do Servidor Público',
        description: `Também conhecido como Dia do Funcionário Público, esta data não é um feriado. Trata-se de um ponto facultativo, ou seja, o governo pode - mas não é obrigado - dispensar os profissionais do serviço público do trabalho nesse dia. O Dia do Servidor Público surgiu através do Conselho Federal do Serviço Público Civil, recordando a criação das leis que regem os direitos e deveres dos servidores públicos - Decreto Lei nº 1.713, de 28 de outubro de 1939.`,
        type: 'event commemorative',
    },
    {
        day: '29/9',
        title: 'Dia Nacional do Livro',
        description: `O Dia do Livro surgiu em homenagem à fundação da Biblioteca Nacional do Livro, em 1810, pela Coroa Portuguesa. Na época, D. João VI trouxe para o Brasil milhares de peças da Real Biblioteca Portuguesa, formando o princípio da Biblioteca Nacional do Brasil (fundada em 29 de outubro de 1810).`,
        type: 'event commemorative',
    },
    {
        day: '31/9',
        title: 'Halloween',
        description: `Dia das Bruxas ou Halloween, é uma celebração observada em vários países, principalmente no mundo anglófono, em 31 de outubro, véspera da festa cristã ocidental do Dia de Todos os Santos.`,
        type: 'event commemorative',
    },
    {
        day: '31/9',
        title: 'Dia do Saci',
        description: `A data homenageia o Saci-Pererê, figura mitológica do imaginário folclórico brasileiro. O Dia do Saci foi criado com o intuito de ajudar a valorizar o folclore nacional, ao invés do Dia das Bruxas (Halloween), que é celebrado no mesmo dia e que nada tem a ver com a cultura do Brasil.`,
        type: 'event commemorative',
    },
    {
        day: '1/10',
        title: 'Dia de Todos os Santos',
        description: `A ideia de homenagear todos os santos teria começado por volta do século IV, na Antioquia, quando se recordavam os santos mártires no primeiro domingo após Pentecostes. Nos primeiros anos da Igreja Católica, estima-se que mais de seis mil santos e beatos foram mortos pelos romanos. Mais tarde, no ano 835 d.C, o papa Gregório IV decidiu dedicar o dia 1º de novembro a todos aqueles que tiveram uma vida santa, mas não foram lembrados ao longo do ano, ou mesmo não foram reconhecidos como santos oficialmente pela Igreja.`,
        type: 'event commemorative',
    },
    {
        day: '2/10',
        title: 'Finados',
        description: `Desde o século XI, os papas Silvestre II, João XVIII e Leão IX já recomendavam os cristãos a dedicarem um dia por ano a rezarem por quem já havia falecido e que não era lembrado. A partir do século XII, o Dia de Finados é celebrado pela Igreja Católica em 2 de novembro.`,
        type: 'event holiday',
    },
    {
        day: '2/10',
        title: 'Dia dos Mortos',
        description: `Conhecido como Día de Muertos, esta é uma comemoração típica do México para celebrar a memória de todas as pessoas queridas, sejam familiares ou amigos que já morreram. Ao contrário do Dia dos Finados, que é celebrado no Brasil em 2 de novembro, o Dia dos Mortos é uma divertida e animada festa, pois as pessoas vão visitar os túmulos dos que já partiram, acendem velas,`,
        type: 'event commemorative',
    },
    {
        day: '8/10',
        title: 'Dia Mundial do Urbanismo',
        description: `O urbanismo consiste nos padrões estabelecidos para o crescimento de uma cidade em vários âmbitos, entre eles o técnico, econômico e administrativo. Em 1949, a Organização Nacional das Nações Unidas (ONU) decide adotar esta data no seu calendário e mais de 30 países seguem este recomendação. O Brasil comemora o Dia do Nacional do Urbanismo na mesma data, de acordo com o Decreto nº 91.900, de 8 de novembro de 1985.`,
        type: 'event commemorative',
    },
    {
        day: '14/10',
        title: 'Dia Nacional da Alfabetização',
        description: `O Dia Nacional da Alfabetização é comemorada desde 14 de Outubro de 1966, criada em homenagem à criação do Ministério da Educação e Cultura (MEC) em 1930, a partir do Decreto de Lei nº 19.402. No Brasil também se comemora o Dia Internacional da Alfabetização, em 8 de Setembro. Esta data foi instituída pela ONU (Organização das Nações Unidas) e possui o mesmo objetivo de fomentar o processo de alfabetização em todos os países do mundo.`,
        type: 'event commemorative',
    },
    {
        day: '15/10',
        title: 'Proclamação da República',
        description: `A Proclamação da República do Brasil foi realizada em 15 de novembro de 1889. O evento aconteceu no Rio de Janeiro, a então capital do país, por um grupo de militares liderado pelo Marechal Deodoro da Fonseca, que deu um golpe de estado no Império.`,
        type: 'event holiday',
    },
    {
        day: '16/10',
        title: 'Dia Internacional da Tolerância',
        description: `O Dia Internacional da Tolerância foi criado em 1996, pela Assembleia Geral da Organização das Nações Unidas (ONU). A ideia surgiu a partir do Ano das Nações Unidas para a Tolerância, em 1995, que foi decidida e programada desde 1993, pela Organização das Nações Unidas para a Educação, a Ciência e a Cultura - UNESCO.`,
        type: 'event commemorative',
    },
    {
        day: '19/10',
        title: 'Dia Mundial do Vaso Sanitário',
        description: `A data pode parecer uma grande brincadeira, mas o assunto não podia ser o mais sério: falta de saneamento básico para bilhões de pessoas! O World Toilet Day, como é conhecido internacionalmente, ajuda a conscientizar as pessoas e os governos sobre a enorme quantidade de pessoas que não possuem acesso à um vaso sanitário limpo e com sistema de saneamento adequado.`,
        type: 'event commemorative',
    },
    {
        day: '19/10',
        title: 'Dia Internacional do Homem',
        description: `Foi Mikhail Gorbatchov, último líder da União Soviética, que promoveu a ideia da criação da data. Sua intenção era homenagear homens que haviam se destacado na história do seu país. Em 1999, A International Men's Day foi comemorada pela primeira vez em Trinidad e Tobago, tendo sido criada pelo Dr. Jerome Teelucksingh, professor de História na Universidade das Índias Ocidentais, com o apoio das Organizações das Nações Unidas (ONU).`,
        type: 'event commemorative',
    },
    {
        day: '25/10',
        title: 'Dia Internacional para a Eliminação da Violência Contra as Mulheres',
        description: `A Organização das Nações Unidas (ONU), desde 1999, reconhece o dia 25 de novembro como o Dia Internacional para a Eliminação da Violência Contra as Mulheres. A data surgiu em decorrência do Dia Latino-americano de Não Violência Contra a Mulher, que foi criada durante o Primeiro Encontro Feminista Latino-Americano e Caribenho de 1981, realizado em Bogotá, Colômbia.`,
        type: 'event commemorative',
    },

        {
        day: '27/10',
        title: 'Dia Nacional de Combate ao Câncer',
        description: `O principal objetivo desta data é alertar a população brasileira sobre os diferentes tipos de tratamentos e, principalmente, como evitar esta doença, considerada a segunda que mais mata no Brasil e no mundo. De acordo com dados da Organização Mundial da Saúde – OMS, aproximadamente 30% das mortes provocadas pelo câncer poderiam ter sido evitadas, caso o paciente tivesse feito o diagnóstico prematuramente, ou com ações preventivas para garantir hábitos de vida mais saudáveis.`,
        type: 'event commemorative',
    },
    {
        day: '1/11',
        title: 'Dia Internacional da Luta contra a AIDS',
        description: `A data tem o objetivo de conscientizar a população sobre uma das doenças que mais mata no mundo: a AIDS. O Dia Mundial de Luta contra a AIDS foi criado pela Organização Mundial da Saúde (OMS), com o apoio da Organização das Nações Unidas (ONU), em uma Assembleia realizada em outubro de 1987.`,
        type: 'event commemorative',
    },
    {
        day: '2/11',
        title: 'Nasce Pedro II',
        description: `Pedro II (1825 – 1891), cognominado como "o Magnânimo", foi o segundo e último monarca do Império do Brasil, tendo imperado no país durante um período de 58 anos. Nascido no Palácio imperial de São Cristóvão, no Rio de Janeiro, foi o filho mais novo do imperador Pedro I do Brasil e da imperatriz consorte Maria Leopoldina de Áustria e, portanto, membro do ramo brasileiro da Casa de Bragança.`,
        type: 'event historical',
    },
    {
        day: '8/22',
        title: 'Dia da Justiça',
        description: `O Dia da Justiça foi estabelecido através do artigo 5º do Decreto de Lei nº 1.408, de 9 de agosto de 1951. A data é considerada feriado em todo o território nacional, ou seja, no Dia da Justiça todos os fóruns e ofícios de Justiça não funcionam. Mesmo sendo oficializado apenas em 1951, o Dia da Justiça é celebrado desde 1940 em referência à imagem da Imaculada Conceição, padroeira da justiça.`,
        type: 'event commemorative',
    },
    {
        day: '10/11',
        title: 'Dia Internacional dos Direitos Humanos',
        description: `No dia 10 de dezembro de 1948, a Assembleia Geral da ONU adotou e proclamou a Declaração Universal dos Direitos Humanos. Em 1950, o dia 10 de dezembro foi estabelecido pela ONU como Dia Internacional dos Direitos Humanos.`,
        type: 'event commemorative',
    },
    {
        day: '13/11',
        title: 'Dia Nacional do Cego',
        description: `O Dia Nacional do Cego foi criado a partir do Decreto nº 51.405, de 26 de julho de 1961, assinado pelo então presidente do Brasil, Jânio da Silva Quadros. A criação da data tem como objetivo consolidar os princípios da Declaração Universal dos Direitos Humanos, que visa os fundamentos de igualdade e solidariedade para todos os cidadãos.`,
        type: 'event commemorative',
    },
    {
        day: '20/11',
        title: 'Dia do Mecânico',
        description: `A data presta homenagem aos chamados "médicos dos carros", principal área de atuação deste profissional. Os mecânicos são os profissionais responsáveis pela manutenção e cuidados dos veículos motorizados, como carros, motocicletas e etc.`,
        type: 'event commemorative',
    },
    {
        day: '21/11',
        title: 'Dia do Atleta',
        description: `Quem decretou o dia 21 de dezembro como sendo o Dia Nacional do Atleta foi o ex-presidente do Brasil Jânio Quadros, através do Decreto nº 51.165, de 8 de agosto de 1961, como forma de honrar os atletas brasileiros que com empenho e dedicação representam o país em competições e elevam a nossa bandeira no mundo.`,
        type: 'event commemorative',
    },
    {
        day: '23/11',
        title: 'Dia do Vizinho',
        description: `Existem algumas divergências sobre a data correta para comemorar o Dia do Vizinho no Brasil. A maioria dos estados brasileiros celebra o 23 de dezembro, no entanto, não existe uma justificativa concreta para a escolha desta data.Em outros lugares do país, os vizinhos comemoram o seu dia em 20 de agosto, em homenagem à figura da poetisa Cora Coralina.`,
        type: 'event commemorative',
    },
    {
        day: '25/11',
        title: 'Natal',
        description: `Atualmente, o Natal é celebrado em quase todos os países do mundo. Independente da religião, praticamente todas as pessoas celebram esta comemoração a sua maneira. As festividades dessa data comemorativa começam na véspera de Natal, dia 24 de dezembro, quando a família se reúne para a ceia e trocam presentes e mensagens de afeto. No cristianismo, a palavra Natal significa “nascimento” e celebra o dia em que o Menino Jesus nasceu. Os relatos bíblicos falam que Jesus foi gerado no ventre da virgem Maria, que estava noiva de José quando foi escolhida para gerar o filho de Deus.`,
        type: 'event holiday',
    },
    {
        day: '28/11',
        title: 'Dia do Salva-vidas',
        description: `Supostamente, a comemoração do dia do salva-vidas é em 28 de dezembro por coincidir com o dia de devoção ao divino anjo Damabiah, responsável pela proteção e auxílio das pessoas que estão ou vivem no mar. Por coincidência, no dia 28 de dezembro de 1970, a Brigada Militar Brasileira formava a primeira equipe de policiais com a função de trabalhar exclusivamente como salva-vidas, na cidade de Porto Alegre.`,
        type: 'event commemorative',
    },
    {
        day: '/',
        title: '',
        description: ``,
        type: 'event commemorative',
    },
]
export {displayEvents, events}